Fix 10: Generating database dumps without sanitizing data #10 (#11)

diff --git a/cloud-teleport b/cloud-teleport
--- a/cloud-teleport
+++ b/cloud-teleport
@@ -22,6 +22,15 @@ function teleport_scp()
 function dump_by_type()
 {
     local type=$1
+    case "$type" in
+      db) type="db -i"
+        ;;
+      code)
+        ;;
+      *) echo "Invalid type: specify code or db";
+         exit 1;
+        ;;
+    esac
     echo "Starting ${type} backup..."
     teleport_send_cmd "php bin/magento support:backup:${type};" && {
     dumpsDirectory="var/support/"
